# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd83bd713bd478985f24e63d7ec664822a5f07326c6df9a525465455005013ba38a2981883a87f1b4b1ecaa27fe6917151137ab5f181d600ba8122d200039a7

test:
  secret_key_base: 9eefc0353199c287e3dd874c457f88ae0c69d9b54e6e220963616b3d72a41a4d071f5d7fb35516838fe6e2b3b3d738e48c2f110daef427c60e8ca7b692997eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
